version: '3'

services:
  kubetest:
    image: afp55/kubetest:latest
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongo
  
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"