apiVersion: v1
kind: Service
metadata:
  name: kubetest
  labels:
    app: kubetest
spec:
  ports:
    - port: 8080
  selector:
    app: kubetest
    tier: app
  type: LoadBalancer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kubetest
  labels:
    app: kubetest
spec:
  selector:
    matchLabels:
      app: kubetest
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubetest
        tier: app
    spec:
      containers:
      - image: afp55/kubetest:latest
        name: kubetest
        env:
        - name: MONGO_HOST
          value: kubetest-mongo-service
        ports:
        - containerPort: 8080
          name: kubetest