apiVersion: v1
kind: Service
metadata:
  name: kubetest-mongo-service
  labels:
    app: kubetest
spec:
  ports:
    - port: 27017
  selector:
    app: kubetest
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: kubetest-mongo-deployment
  labels:
    app: kubetest
spec:
  selector:
    matchLabels:
      app: kubetest
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubetest
        tier: mongo
    spec:
      containers:
      - image: mongo:3.4
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo