apiVersion: v1
kind: Service
metadata:
  name: kubetest
  labels:
    service: kubetest
spec:
  ports:
  - name: "kubetest-port"
    port: 8080
    targetPort: 8080
  selector:
    service: kubetest
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: kubetest
  name: kubetest
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: kubetest
    spec:
      containers:
      - image: afp55/kubetest:latest
        name: kubetest
        env:
        - name: MONGO_HOST
          value: mongo
        ports:
        - containerPort: 8080
      restartPolicy: Always
