apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongo
  name: mongo
spec:
  ports:
  - name: "mongo-port"
    port: 27017
    targetPort: 27017
  selector:
    service: mongo
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mongo
  name: mongo
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
      - image: mongo:3.4
        name: mongo
        ports:
        - containerPort: 27017
      restartPolicy: Always
