apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: kubetest
  name: kubetest
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kubetest
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          value: mongo
        image: afp55/kubetest:latest
        name: kubetest
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
